// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/skayfish/metrics/internal/server/storage (interfaces: DatabaseStorage)

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/skayfish/metrics/internal/model"
)

// MockDatabaseStorage is a mock of DatabaseStorage interface.
type MockDatabaseStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseStorageMockRecorder
}

// MockDatabaseStorageMockRecorder is the mock recorder for MockDatabaseStorage.
type MockDatabaseStorageMockRecorder struct {
	mock *MockDatabaseStorage
}

// NewMockDatabaseStorage creates a new mock instance.
func NewMockDatabaseStorage(ctrl *gomock.Controller) *MockDatabaseStorage {
	mock := &MockDatabaseStorage{ctrl: ctrl}
	mock.recorder = &MockDatabaseStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseStorage) EXPECT() *MockDatabaseStorageMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDatabaseStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDatabaseStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDatabaseStorage)(nil).Close))
}

// Get mocks base method.
func (m *MockDatabaseStorage) Get(arg0 string) (*model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDatabaseStorageMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDatabaseStorage)(nil).Get), arg0)
}

// GetAll mocks base method.
func (m *MockDatabaseStorage) GetAll() ([]model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDatabaseStorageMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDatabaseStorage)(nil).GetAll))
}

// GetAllContext mocks base method.
func (m *MockDatabaseStorage) GetAllContext(arg0 context.Context) ([]model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllContext", arg0)
	ret0, _ := ret[0].([]model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllContext indicates an expected call of GetAllContext.
func (mr *MockDatabaseStorageMockRecorder) GetAllContext(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllContext", reflect.TypeOf((*MockDatabaseStorage)(nil).GetAllContext), arg0)
}

// GetContext mocks base method.
func (m *MockDatabaseStorage) GetContext(arg0 context.Context, arg1 string) (*model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext", arg0, arg1)
	ret0, _ := ret[0].(*model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContext indicates an expected call of GetContext.
func (mr *MockDatabaseStorageMockRecorder) GetContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockDatabaseStorage)(nil).GetContext), arg0, arg1)
}

// PingContext mocks base method.
func (m *MockDatabaseStorage) PingContext(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingContext", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingContext indicates an expected call of PingContext.
func (mr *MockDatabaseStorageMockRecorder) PingContext(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingContext", reflect.TypeOf((*MockDatabaseStorage)(nil).PingContext), arg0)
}

// Update mocks base method.
func (m *MockDatabaseStorage) Update(arg0 model.Metrics) (*model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(*model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDatabaseStorageMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDatabaseStorage)(nil).Update), arg0)
}

// UpdateContext mocks base method.
func (m *MockDatabaseStorage) UpdateContext(arg0 context.Context, arg1 model.Metrics) (*model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContext", arg0, arg1)
	ret0, _ := ret[0].(*model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContext indicates an expected call of UpdateContext.
func (mr *MockDatabaseStorageMockRecorder) UpdateContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContext", reflect.TypeOf((*MockDatabaseStorage)(nil).UpdateContext), arg0, arg1)
}
